# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Carangas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carangas
	pod 'Alamofire'
        pod 'SideMenu'
	

end
